# syntax=docker/dockerfile:1
#
# WellPulse v2 — Phase 10 (Section 22): Dockerfile for the FastAPI
# service.
#
# Both stages below are anchored at the SAME WORKDIR (/app) on
# purpose. MLflow bakes an absolute artifact path into an experiment
# PERMANENTLY at creation time (src/experiments/mlflow_utils.py's
# ARTIFACT_ROOT.resolve().as_uri()) — this has resurfaced every phase
# so far whenever mlflow.db/mlruns/ moved to a new machine, because
# the recorded path only ever resolves correctly on the machine that
# created it. Building the registry INSIDE this image, at the exact
# path it will later run at, fixes that permanently for Docker: it no
# longer matters which host or CI runner ran `docker build` — the path
# baked into mlflow.db always matches this image's own /app, because
# both stages share it.
#
# ---- Stage 1: trainer -----------------------------------------------
# "Trainer" is a slight misnomer worth being precise about: this stage
# does NOT re-run baseline/advanced/tuning (make baseline / advanced /
# tune). models/final_model.joblib and models/phase4_best_model.joblib
# are already committed to this repo (unlike mlflow.db/mlruns/, which
# ARE gitignored — see .gitignore) precisely so a fresh checkout never
# needs to retrain anything to reproduce the registered Production
# model. Re-running the full training/tuning chain on every `docker
# build` would mean Phase 11's CI retrains a model on every code push
# — exactly what Section 23 rules out ("retraining is a separate,
# scheduled pipeline... conflating them would mean every typo fix
# retrains a model unnecessarily"). This stage's only job is
# REGISTRATION: take the already-trained model and log/register it
# into a tracking store rooted at this image's own filesystem.
FROM python:3.12-slim AS trainer
WORKDIR /app

COPY requirements-serve.txt .
RUN pip install --no-cache-dir -r requirements-serve.txt

# Only what src.experiments.register_final_model's import chain
# touches (src/, the raw dataset, and both committed model bundles) —
# not notebooks/, scripts/, tests/, docs/, or reports/ (those either
# aren't needed at all here, or get freshly regenerated by the command
# below as a side effect).
COPY src/ ./src/
COPY data/raw/ ./data/raw/
COPY models/ ./models/

# Logs one MLflow run for the already-trained final model, registers
# it, and moves the Production alias to it per Section 17's promotion
# criteria — writing mlflow.db + mlruns/ fresh, rooted at /app.
# Deterministic given the committed inputs above (random_state=42
# throughout), so this reproduces the same Production model every
# build.
RUN python -m src.experiments.register_final_model

# ---- Stage 2: runtime -------------------------------------------------
# Only what GET /health, POST /api/v1/predict, and the /checkins
# endpoints actually touch at request time. Training/EDA code's
# heavier dependencies (lightgbm, xgboost, seaborn, nbformat/nbclient/
# ipykernel — see requirements.txt) never enter this image at all: it
# installs requirements-serve.txt, not requirements.txt (Section 22:
# "training/EDA code is not baked into the serving image").
FROM python:3.12-slim AS runtime
WORKDIR /app

COPY requirements-serve.txt .
RUN pip install --no-cache-dir -r requirements-serve.txt

COPY src/ ./src/
COPY static/ ./static/
COPY data/raw/ ./data/raw/
COPY models/ ./models/

# The registry/tracking store the trainer stage produced — copied
# from THAT stage (not rebuilt here) so the runtime image serves
# exactly the run the trainer stage registered, never a second,
# potentially-different one.
COPY --from=trainer /app/mlflow.db ./mlflow.db
COPY --from=trainer /app/mlruns/ ./mlruns/

# No HEALTHCHECK here — docker-compose.yml defines one so it can also
# gate the api service's own start-up ordering relative to db; a
# second, differently-configured HEALTHCHECK on the image itself would
# just be a second source of truth to keep in sync.
EXPOSE 8000
CMD ["uvicorn", "src.api.main:app", "--host", "0.0.0.0", "--port", "8000"]
